### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by bxyster** [SOM-Research/Gitana#1]
Hi,

I got error message "TypeError: 'Head' object does not support indexing" while updating DB

Thanks

**Comment by valeriocos** [comment]
Hi @bxyster, the issue should be fixed now

**Comment by bxyster** [comment]
Hi, @valeriocos , 

thanks for you help.. But I got another error message "TypeError: sequence item 0: expected string, bytearray found" while Export DB to JSON, the last line should be "diff_content = '\n'.join(diff_content)"

Sorry to trouble you again!

**Comment by valeriocos** [comment]
you're welcome @bxyster !
I run the db2json export with some examples I have, but I didn't get any error.
Could you report the problem you have to another issue  and include the stack trace?

**Comment by bxyster** [comment]
Hi, @valeriocos ,
With Traceback below, Is that because the form should be filled with no empty? I only set the DB name, and the others remain default.

Traceback (most recent call last):
  File "db2json_gui.py", line 241, in execute_export
    g.db2json(self.DBNAME, self.OUTPUT_JSON, self.LINE_DETAILS)
  File "/root/Gitana/gitana.py", line 44, in db2json
    exporter.export()
  File "/root/Gitana/db2json.py", line 405, in export
    self.add_file_info_to_json(repo_json)
  File "/root/Gitana/db2json.py", line 372, in add_file_info_to_json
    changes_info = self.get_changes_for_file(file_history)
  File "/root/Gitana/db2json.py", line 223, in get_changes_for_file
    return self.get_modification_info_per_file(file_history)
  File "/root/Gitana/db2json.py", line 174, in get_modification_info_per_file
    patch_info = self.get_patch_info(patch)
  File "/root/Gitana/db2json.py", line 71, in get_patch_info
    diff_content = self.get_diff_content(content)
  File "/root/Gitana/db2json.py", line 61, in get_diff_content
    diff_content = '\n'.join(diff_content)
TypeError: sequence item 0: expected string, bytearray found

Thanks again

**Comment by valeriocos** [comment]
the form can be filled with no empty values.
could you send me the dump of your database (you can upload it in GitHub and just tell me the repository to clone)?

**Comment by bxyster** [comment]
I clone from https://github.com/SOM-Research/busfactor.git as example repository

and I dump the database use mysqldump

You can download sql file by accessing https://github.com/bxyster/mytest

And if you want to restore , you can use mysql -uuser -ppassword builder_busfactor < builder_busfactor.sql

Now if you use database I provide , You should got same Traceback after Export DB to JSON like below:

Traceback (most recent call last):
  File "db2json_gui.py", line 241, in execute_export
    g.db2json(self.DBNAME, self.OUTPUT_JSON, self.LINE_DETAILS)
  File "/root/Gitana/gitana.py", line 44, in db2json
    exporter.export()
  File "/root/Gitana/db2json.py", line 405, in export
    self.add_file_info_to_json(repo_json)
  File "/root/Gitana/db2json.py", line 372, in add_file_info_to_json
    changes_info = self.get_changes_for_file(file_history)
  File "/root/Gitana/db2json.py", line 223, in get_changes_for_file
    return self.get_modification_info_per_file(file_history)
  File "/root/Gitana/db2json.py", line 174, in get_modification_info_per_file
    patch_info = self.get_patch_info(patch)
  File "/root/Gitana/db2json.py", line 71, in get_patch_info
    diff_content = self.get_diff_content(content)
  File "/root/Gitana/db2json.py", line 61, in get_diff_content
    diff_content = '\n'.join(diff_content)
TypeError: sequence item 0: expected string, bytearray found

**Comment by valeriocos** [comment]
I don't get any error. I have just sent you a pull request with the json output for your example repository.

In the code of the db2json.py, the problem comes from:
```
if re.match(r"^@@(\s|\+|\-|\d|,)+@@", lines[0], re.M):
   first_line_content = lines[0].split("@@")[2]
   diff_content = lines[1:]
   diff_content.insert(0, first_line_content)
   diff_content = '\n'.join(diff_content)
```
where `diff_content` instead of being a string is an array. It means probably that `first_line_content` is not a string but an array. I need that diff that is causing the problem, to fix the code.

**Comment by bxyster** [comment]
I'm a little confused about it.. 

I write a test script , but it works 

#!/usr/bin/python

import MySQLdb
import re

def get_info_from_db():

  patch=""

  # Open database connection
  db = MySQLdb.connect("127.0.0.1", "user","password", "builder_busfactor")

  # prepare a cursor object using cursor() method
  cursor = db.cursor()

  # execute SQL query using execute() method
  cursor.execute("SELECT c.author_id, a.name, a.email, com.name, com.email, c.sha, c.committed_date, c.authored_date, fm.additions, fm.deletions, fm.patch FROM (SELECT * FROM file_modification fm WHERE file_id in (1)) as fm JOIN (SELECT * FROM commit WHERE repo_id = 1) as c ON c.id = fm.commit_id JOIN developer a ON c.author_id = a.id JOIN developer com ON c.committer_id = com.id GROUP BY c.author_id, c.committer_id, c.authored_date ORDER BY c.authored_date DESC;")

  # Fetch a single rew using fetchone() method.
  #data = cursor.fetchall()
  row = cursor.fetchone()
  while row:
    patch = row[10]
    row = cursor.fetchone()

  # disconnect from server
  db.close()
  return patch

patch = get_info_from_db()
if patch:
  lines = patch.split('\n')
  if re.match(r"^@@(\s|\+|\-|\d|,)+@@", lines[0], re.M):
    first_line_content = lines[0].split("@@")[2]
    diff_content = lines[1:]
    diff_content.insert(0, first_line_content)
    diff_content = '\n'.join(diff_content)
    print type(diff_content)
 

And when I comment the line 

#first_line_content = lines[0].split("@@")[2]
#diff_content.insert(0, first_line_content)

It appears same Error messages

**Comment by valeriocos** [comment]
I don't know how I can help you. I don't know how to replicate the error you have.

**Comment by bxyster** [comment]
hi, Can the following messages become clues?

This works in py3k but not in 2.x. I don't know if it is deliberate:

Python 3.0b2+ (py3k, Jul 27 2008, 12:52:40) 
[GCC 4.3.1 20080626 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> b"".join([bytearray(b"")])
b''

Python 2.6b2+ (trunk, Aug  1 2008, 01:47:52) 
[GCC 4.3.1 20080626 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> b"".join([bytearray(b"")])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: sequence item 0: expected string, bytearray found

**Comment by valeriocos** [comment]
I don't think so.
Are you having this problem with the example repository you linked above (https://github.com/SOM-Research/busfactor.git as example repository), or with another repository?

In case you are using a different one, could you isolate and send me the patch causing this problem (you can modify the method ```get_modification_info_per_file``` to get SHA of the commit related to the patch in question)?

**Comment by bxyster** [comment]
I solved by modify in the line 192 of db2json.py with  
patch = str(row[10]) 

Not sure why!

I load Gitana ,busfactor  and take it for a spin.  It work and running pretty with few files and branches. But It will take long long time as the files and branches become increasingly, Take my own repository (with only 7M for bare repository and have 900 branches ) as a example, The Volume of the JSON file generated has more than 10G, And actually, I have repository more than 1G......

Is that to say it's more suited to use JSON file and busfactor for few files and branches? Or could you kindly tell if there are work arround for displaying Big Repository like busfactor.

**Comment by valeriocos** [comment]
ok thanks, I'll update the code (however it could nice to understand what the problem was, since I was not able to replicate the error with the repository you used as example).

In order to handle large repositories, currently, you can use a filter to reduce the number of resources (files, branches, etc.) to analyse. You may want to have a look to the folder settings (https://github.com/SOM-Research/Gitana/blob/master/settings/). There, you will find 3 different types of file:
*.fex used to filter files with a given extensions
*.frs used to filter branches, directories and files
*.nal used to merge user identities

I hope this will help

**Comment by bxyster** [comment]
Many thanks!

I try several repositories and they all appear same errors including (https://github.com/SOM-Research/busfactor.git) if I don't modify the file I mentioned above

So I think it's something about  Environment Variable  or OS or Python Version or something relating with my PC environment

**Comment by bxyster** [comment]
Hi @valeriocos 

Sorry to bother again!

I found the filter function was needed by output.json which may cost several hours to generate according the size of the repository,  Has Gitana already have some method to skip the process of generating output.json to filter directly or need redesign? Because I have a  lot of repositories which need update everyday and it takes long long time and space to store the file.

Thanks

**Comment by valeriocos** [comment]
Hi @bxyster 
currently, there is no method to skip the generation of the output.json.
