### ISSUE TITLE
package stucture seems wrong.

### ISSUE THREAD

**Issue by mopuru-murali** [SOM-Research/Gitana#16]
Installed Gitana to my Anaconda2 and faced following problem

	>>> from gitana import Gitana
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	ImportError: cannot import name Gitana
	>>> import sys
	>>> for i in sys.path:
	...    print i
	...

	/dbc/blr-dbc301/mmopuru/anaconda2/lib/python27.zip
	/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7
	/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/plat-linux2
	/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/lib-tk
	/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/lib-old
	/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/lib-dynload
	/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages
	/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/Sphinx-1.5.6-py2.7.egg
	/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/gitana-1.0-py2.7.egg
	/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/pygal-2.3.1-py2.7.egg
	/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/slacker-0.9.50-py2.7.egg
	/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/BeautifulSoup-3.2.1-py2.7.egg
	/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/py_stackexchange-2.2.6-py2.7.egg
	/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/selenium-3.4.3-py2.7.egg
	/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/PyGithub-1.34-py2.7.egg
	/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/python_bugzilla-2.1.0-py2.7.egg
	/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/GitPython-2.1.5-py2.7.egg
	/dbc/blr-dbc301/mmopuru/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg

it seems gitana module is under a package gitana. so how does it would work?

**Comment by valeriocos** [comment]
It should be `from gitana.gitana import Gitana`
The examples in the README.md were not updated (I've fixed them now).  To see how to use Gitana, you can have a look at the documentation (http://gitanadocs.getforge.io/examples)
