### ISSUE TITLE
replace mysql-connector dependency with mysql-connector-python-rf 

### ISSUE THREAD

**Issue by mopuru-murali** [SOM-Research/Gitana#17]
Though mysql-connector installed as per setup.py for gitana 
	>>> from gitana import Gitana
throwing error saying
	ImportError: No module named mysql.connector
so better replace mysql-connector dependency with mysql-connector-python-rf in setup.py under install_requires.

**Comment by valeriocos** [comment]
Thanks for reporting this issue. The mysql-connector dependency has been replaced with mysql-connector-python-rf
