### ISSUE TITLE
add py-stackexchange, beautifulsoup, slacker, pygal into install_requires

### ISSUE THREAD

**Issue by mopuru-murali** [SOM-Research/Gitana#18]
add py-stackexchange, beautifulsoup, slacker, pygal into install_requires because these are direct dependencies for stackoverflow, slacker, reports, etc plugins

**Comment by valeriocos** [comment]
they are already declared into the install_requires (https://github.com/SOM-Research/Gitana/blob/master/setup.py)

**Comment by mopuru-murali** [comment]
im sorry may be my codebase was little old. thanks for your reply.
