### ISSUE TITLE
set global innodb_file_per_table=1;

### ISSUE THREAD

**Issue by mopuru-murali** [SOM-Research/Gitana#20]
DatabaseError: 1709 (HY000): Index column size too large. The maximum column size is 767 bytes.

Faced this err though necessary globals set in mysql. Fixed by setting following in mysql server 5.5 instance.

	set global innodb_file_per_table=1;

	mysql> show global variables like 'innodb_file%';
	+--------------------------+-----------+
	| Variable_name            | Value     |
	+--------------------------+-----------+
	| innodb_file_format       | Barracuda |
	| innodb_file_format_check | ON        |
	| innodb_file_format_max   | Barracuda |
	| innodb_file_per_table    | ON        |
	+--------------------------+-----------+
	4 rows in set (0.00 sec)

**Comment by valeriocos** [comment]
As reported in the technical details section in the readme.md and in the documentation (http://gitanadocs.getforge.io/introduction) , you can see that the MySQL server version to be used should be >= 5.6.
Note that one of the difference between MySQL server 5.5 and 5.6 is that innodb_file_per_table is ON by default.

**Comment by mopuru-murali** [comment]
yes i know it. I've upgraded mysql from 5.1 to 5.5. may be this was reason for this non-sync.
