### ISSUE TITLE
reports database is not getting created by default

### ISSUE THREAD

**Issue by mopuru-murali** [SOM-Research/Gitana#21]
g = Gitana(CONFIG, None)
	g.export_to_graph("_papyrus_db", "./graph.json", "./graph.gexf")
	g.export_to_report("_papyrus_db", "./report.json", "./report.html")

reports database not being created by gitana by default.

	mysql.connector.errors.ProgrammingError: 1049 (42000): Unknown database '_papyrus_db'

Thought of doing

	g.init_db("_papyrus_db")

but it will create all the unrelated tables inside it.

**Comment by valeriocos** [comment]
I've just noticed that the examples for the report and graph exporters are not clear, they should be improved.
In order to generate a report, you should before import the data to the gitana db. For instance:

    g = Gitana(CONFIG, None)
    g.init_db("papyrus_db")

    g.create_project("papyrus_db", "papyrus")
    g.import_git_data("papyrus_db", "papyrus", "papyrus_repo", "...\\Desktop\\org.eclipse.papyrus", None, 1, None, 20)
    g.import_bugzilla_tracker_data("papyrus_db", "papyrus", "papyrus_repo", "papyrus-bugzilla", "https://bugs.eclipse.org/bugs/xmlrpc.cgi", "papyrus", None, False, 20)
    g.import_eclipse_forum_data("papyrus_db", "papyrus", "papyrus-forum", "https://www.eclipse.org/forums/index.php/f/121/", None, False, 5)
    g.import_stackoverflow_data("papyrus_db", "papyrus", "papyrus-so", None, False, ['YOUR-TOKEN-1', 'YOUR-TOKEN-2', ...])
	
    g.export_to_graph("_papyrus_db", "./graph.json", "./graph.gexf")
    g.export_to_report("_papyrus_db", "./report.json", "./report.html")

**Comment by mopuru-murali** [comment]
I'm already running after imported data into db using different script.
