### ISSUE TITLE
remove keywords/tokens as names of db tables and its columns

### ISSUE THREAD

**Issue by mopuru-murali** [SOM-Research/Gitana#24]
I see db tables with names 'commit', 'file', 'user' and column names 'size'. I think its better to change names for these to avoid unnecessary conflicts when running it. I faced couple of problems with it when tried reusing Gitana codebase for non-MySQL RDBMS.

**Comment by valeriocos** [comment]
Thanks for reporting this issue, but currently Gitana supports only MySQL db (see technical details in the documentation). However, as soon as other db systems are integrated to Gitana, your proposal will be taken into account.

Note also that supporting another db system may affect the DAO  and DbSchema classes (see importers/) and queries.json (see exporters/resources/) which rely on the MySQL SQL dialects
