### ISSUE TITLE
busfactor project seems to be no longer compatible

### ISSUE THREAD

**Issue by Namingwaysway** [SOM-Research/Gitana#32]
See issue: https://github.com/SOM-Research/busfactor/issues/3 On the other project.

The related error is below:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: Gitana instance has no attribute 'export_json'

According to the source, this seems to no longer be a function that's defined for the object.  Perhaps the function changed or was renamed?

**Comment by jlcanovas** [comment]
Got it, you can see the answer at SOM-Research/busfactor#3
