### ISSUE TITLE
Project creation fails

### ISSUE THREAD

**Issue by ubaierbhat** [SOM-Research/Gitana#34]
Project creation fails. I get the following error

`mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'db_2048.project' doesn't exist`

```python
g = Gitana(CONFIG, None)
g.delete_previous_logs()
g.init_db("db_2048")
g.create_project("db_2048", "2048")
```

**Comment by valeriocos** [comment]
Hi @ubaierbhat , in case you are not bound to use Gitana, I would suggest you to have a look to [Perceval](https://github.com/chaoss/grimoirelab-perceval), which is able to fetch data from many data sources (git, github, gitlab, slack, twitter). Furthermore Perceval can be also used to automatically create visualizations for your software project (more info at [chaoss.github.io/grimoirelab ](https://chaoss.github.io/grimoirelab/))

**Comment by ubaierbhat** [comment]
I wanted to try out [busfactor](https://github.com/SOM-Research/busfactor) which required Gitana.

**Comment by valeriocos** [comment]
I see. Do you have mysql installed in your machine (https://github.com/SOM-Research/Gitana#requirements)?

**Comment by ubaierbhat** [comment]
Yes that is installed. Database is created by without any tables after `g.init_db("db_2048")` but no tables

**Comment by ubaierbhat** [comment]
Sorry. false alarm. Wrong mysql version.

**Comment by ubaierbhat** [comment]
g.export_json() has been removed from 🤦‍♂️ Gitana (I can't even find it in any older version) and as I understand it won't be fixed https://github.com/SOM-Research/busfactor/issues/3

**Comment by valeriocos** [comment]
Try this one: https://github.com/valeriocos/Gitana

**Comment by ubaierbhat** [comment]
Thanks. Found the fork just before reading your comment :)

**Comment by valeriocos** [comment]
You're welcome @ubaierbhat :)
