### ISSUE TITLE
Docs site has gone away

### ISSUE THREAD

**Issue by jean** [SOM-Research/Gitana#35]
http://gitanadocs.getforge.io/

404

That file couldn't be found.

**Comment by Gnafu** [comment]
The was a [readthedocs site](https://gitana.readthedocs.io/en/latest/) but it is a little outdated so I created a new one that builds the latest documentation version:

https://gitana-2021.readthedocs.io/en/latest/

**Comment by jlcanovas** [comment]
Thanks @Gnafu for the effort. From our side, the tool has been archived and we cannot maintain it anymore. The development status of our tools is declared [here](https://som-research.uoc.edu/research-tools/)
