### ISSUE TITLE
install `beautifulsoup` module failed when exec `python setup.py install`

### ISSUE THREAD

**Issue by harkue** [SOM-Research/Gitana#36]
I got this error message:
```
Installed c:\python27\lib\site-packages\gitana-1.0-py2.7.egg
Processing dependencies for gitana==1.0
Searching for beautifulsoup
Reading https://pypi.org/simple/beautifulsoup/
Download error on https://pypi.org/simple/beautifulsoup/: ('_ssl.c:711: The handshake operation timed out',) -- Some packages may not be found!
Couldn't find index page for 'beautifulsoup' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
```

Can anyone help me to fix this problem?

**Comment by gustawdaniel** [comment]
I see that you have the same problem that i described in #38 

There is fragment of official docs:

> Beautiful Soup 3 was the official release line of Beautiful Soup from May 2006 to March 2012. It does not support Python 3 and was discontinued or January 1, 2021—one year after the Python 2 sunsetting date. If you have any active projects using Beautiful Soup 3, you should migrate to Beautiful Soup 4 as part of your Python 3 conversion.

https://www.crummy.com/software/BeautifulSoup/

**Comment by jlcanovas** [comment]
Hi everyone, this tool has been archived and is not maintained anymore. Also, sorry to inform you that we cannot offer additional support. 

The development status of our tools is declared [here](https://som-research.uoc.edu/research-tools/)
